suppress:
 - "ckv-gcp-68" #Ensure IAM policies does not allow permissions management / resource exposure without constraints
 - "tfsec-gcp012" #Ensure IAM policies does not allow write access without constraints
   #10-03-2022 False positive because these policies are least privelege for the KMS keys and Lambda
 - "ckv-gcp-67"
